SunkenChair         = "Legendary"
IronChair           = "Rare"
DiamondChair        = "Rare"
RainbowChair        = "Rare"
CherryBlossomChair  = "Legendary"
ObsidianChair       = "Legendary"
FrostChair          = "Divine"
MagmaChair          = "Divine"