local ReplicatedStorage = game:GetService("ReplicatedStorage")

return {
    SunkenChair             = ReplicatedStorage.Resources.Prefabs.Chairs.SunkenChair,
    MossyCobblestoneChair   = ReplicatedStorage.Resources.Prefabs.Chairs.MossyCobblestoneChair,
    DiamondChair            = ReplicatedStorage.Resources.Prefabs.Chairs.DiamondChair,
    RainbowChair            = ReplicatedStorage.Resources.Prefabs.Chairs.RainbowChair,
    CherryBlossomChair      = ReplicatedStorage.Resources.Prefabs.Chairs.CherryBlossomChair,
    ObsidianChair           = ReplicatedStorage.Resources.Prefabs.Chairs.ObsidianChair,
    FrostChair              = ReplicatedStorage.Resources.Prefabs.Chairs.FrostChair,
    MagmaChair              = ReplicatedStorage.Resources.Prefabs.Chairs.MagmaChair,
}