local ReplicatedStorage = game:GetService("ReplicatedStorage")

return {
    SunkenChest         = ReplicatedStorage.Resources.Prefabs.RegularChests.SunkenChest,
    IronChest           = ReplicatedStorage.Resources.Prefabs.RegularChests.IronChest,
    DiamondChest        = ReplicatedStorage.Resources.Prefabs.RegularChests.DiamondChest,
    RainbowChest        = ReplicatedStorage.Resources.Prefabs.RegularChests.RainbowChest,
    CherryBlossomChest  = ReplicatedStorage.Resources.Prefabs.RegularChests.CherryBlossomChest,
    ObsidianChest       = ReplicatedStorage.Resources.Prefabs.RegularChests.ObsidianChest,
    FrostChest          = ReplicatedStorage.Resources.Prefabs.RegularChests.FrostChest,
    MagmaChest          = ReplicatedStorage.Resources.Prefabs.RegularChests.MagmaChest,
}