SunkenChest             = "Legendary"
IronChest   = "Rare"
DiamondChest            = "Rare"
CherryBlossomChest      = "Legendary"
RainbowChest            = "Rare"
ObsidianChest           = "Legendary"
FrostChest              = "Divine"
MagmaChest              = "Divine"